# Étape 1: Construction de l'application React
FROM node:18 AS builder

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers package.json et package-lock.json depuis le dossier frontend
COPY frontend/package*.json ./

# Installation des dépendances
RUN npm install

# Copie de tous les fichiers restants du frontend dans le conteneur
COPY frontend/ ./

# Construction de l'application React
RUN npm run build

# Étape 2: Nginx pour servir l'application React
FROM nginx:alpine

# Copie de la configuration Nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

# Copie de l'application construite dans le répertoire de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Exposer le port 80 pour Nginx
EXPOSE 80

# Commande de démarrage de Nginx
CMD ["nginx", "-g", "daemon off;"]
