# Étape 1 : Construction de l'application Node.js
FROM node:18 AS builder

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier package.json et package-lock.json dans le répertoire de travail
COPY backend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier tous les fichiers de l'application dans le conteneur
COPY backend/ ./

# Exposer le port sur lequel le serveur écoute (exemple: 5000)
EXPOSE 5000

# Commande pour démarrer le serveur backend 
CMD ["node", "server.js"]
